# Generated by Django 4.2 on 2023-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('hotel_address', models.CharField(max_length=200)),
                ('avelable_room', models.CharField(max_length=50)),
                ('hotel_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
