# Generated by Django 4.2 on 2023-09-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=20)),
                ('room_image', models.ImageField(upload_to='images/')),
                ('room_image2', models.ImageField(upload_to='images/')),
                ('hotel_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.hotel')),
                
            ],
        ),
    ]
