# Generated by Django 4.2 on 2023-09-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
