# Generated by Django 4.2 on 2023-10-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField(max_length=5)),
                ('hotel_id', models.IntegerField(max_length=5)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
